{
 "title": "Orders Service",
 "description": "Параметры микросервисов отвечающих за функционирования сервиса заказов.\norders-handler + orders-storage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Orders Storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"order-storage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders Handler",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"orders-handler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=\"order-storage\", instance=\"localhost:8081\", id=\"direct\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders GET",
   "type": "timeseries",
   "description": "/orders",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"orders-handler\", uri=\"/orders\", exception=\"none\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}